config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "restaurants#index"
  #get "restaurants", to: "restaurants#index"

  #get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  #post "restaurants", to: "restaurants#create"

  #get "restaurants/:id", to: "restaurants#show", as: "restaurant"

  #get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  #patch "restaurants/:id", to: "restaurants#update"
  #delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: {in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false}
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, numericality: {only_integer: true, in: 0..5}
  validates :content, presence: true
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :get_restaurant, only: [:show] #don't use :create here since does not exist!

  def index
    @restaurants = Restaurant.all
  end

  def show
    #can leave it empty since get_restaurant before!
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end


  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    redirect_to review_path(@review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.title %> restaurant</h1>
<%= render "form" %>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
    <br>
<%= link_to "Delete", restaurant_path(restaurant), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<%= link_to "Go back", root_path %>

<br>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Add a new review</h1>
<%= form_with model: @review do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>